name: Build ios dev self-hosted

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

jobs:
  build_and_distribute:
    runs-on: self-hosted
    env:
      environment: DEV
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.0.2

      - name: Flutter check version
        run: flutter --version

      - name: Melos activation
        run: flutter pub get
      
      - name: Install pod
        run: cd ios && pod install

      - name: Bumblebee Transform Ios
        run: flutter build ios

